### ISSUE TITLE
KoGaPlanet doesn't load games

### ISSUE THREAD

**Issue by Sukeeto** [Finalshare90/kogaplanet-launcher#11]
I tested the games available on KoGaPlanet in version 3.0.0 and most of them didn't load.
The planet code is ok (apparently)

Of the ones I tested, _[Kogatown](https://www.kogaplanet.com/planet/5)_ was the only one that worked.

https://user-images.githubusercontent.com/82664951/229299585-1f504893-c79a-4158-9126-98ea2b95cc16.mp4

**Comment by Finalshare90** [comment]
The planet's names is Case-sensitive, try putting the name exactly equals to the folder name.

**Comment by Finalshare90** [comment]
Also, could you send one of theses games for me on discord?

**Comment by Sukeeto** [comment]
> The planet's names is Case-sensitive, try putting the name exactly equals to the folder name.

![image](https://user-images.githubusercontent.com/82664951/229302008-3992a2f8-7ba1-451c-b760-e6a68353b121.png)
I put it exactly as written in the "Jamesville" folder

**Comment by Finalshare90** [comment]
It was a unhanded exception for spawnpoint tag, error mine.
To clarify, i forgot to put a "Plan B" in-case the player didn't put their spawnpoint tag, or keep your data NULL.
A path-fix will come out asp.

**Comment by Finalshare90** [comment]
Patch at [5b275f0](https://github.com/Finalshare90/kogaplanet-launcher/commit/5b275f01b80eb6aab65bceb9120770fdc4ee6d91), enjoy your saturday!
